ports:
- port: 8000
  onOpen: open-preview
tasks:
- init: >
    composer update
  command: >
    cp .env.example .env
    php artisan key:generate
    php artisan migrate
    php artisan passport:install
    php artisan --host=0.0.0.0 --port=8000
